# Generated by Django 2.0.7 on 2019-02-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='occupation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
