# Generated by Django 2.0.7 on 2019-02-09 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190209_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
